### ISSUE TITLE
Add column "Date Added"

### ISSUE THREAD

**Issue by gavinhughes** [hssm/advanced-browser#101]
I would like to be able to insert a “**Date Added**” column so I can sort by that field. This is very useful when importing a deck. The **created** date is the date the card was created before import. The **added** date is the date all the cards we’re added upon import, which is generally more useful once cards have be imported.

**Comment by hssm** [comment]
Unfortunately Anki does not retain that kind of data, so there's nothing I can add to support that column. You may find [this add-on](https://ankiweb.net/shared/info/217650262) useful. It should let you update your notes' creation times so you can work with the `Created Date` column again.
