### ISSUE TITLE
Selections and list sort order issues

### ISSUE THREAD

**Issue by jsmars** [hssm/advanced-browser#103]
I would like to reschedule only cards that I haven't yet seen by a different column. (and similar functionality)

**Expected method:** 
I sort by due date, and select all my new card, after that I would like to sort by a different column, and and then press re-schedule to have them rescheduled in the order that I then see them. Currently when resorting the list, the selection is lost. Normal behavior for windows form lists is that the selection is kept. Is there any way to make this happen?

Requested fix 1:
When sorting by column, previous card selection is kept.

**Related issue:**
Also, a related issue is that when rescheduling is pressed, it seems that the order in which they are rescheduled is not in fact the current list order, but rather in the order which they were selected. So even if the above was fixed, the order may stay the same since they were selected originally in a different order. 
I noticed this to achieve the original goal manually, I sorted by my new column, and when through and manually selected all the cards in the list that were marked as new, but since I didn't do this in the same order as the new column, when I rescheduled them, the order was not in the sorted order from the column I wanted, so I had to manually press reschedule on each card in the proper order.

**Requested fix 2:**
When pressing reschedule (and other actions) on a selection in the list, perform the action in the current list order from top to bottom.

I hope that was clear enough so you understand the issue! Also, let me know if I'm missing something and there was already an easier way to do this, but I believe these fixes would be good regardless, since it opens up a lot of functionality in using the plugin. 

Thanks for all your work on this plugin so far, it's really vital to anki!

**Comment by hssm** [comment]
The default browser already does both of these things.
