### ISSUE TITLE
Some columns can only be viewed in ascending order, part 2

### ISSUE THREAD

**Issue by ijgnd** [hssm/advanced-browser#104]
First of all: Thanks creating and maintaining this essential add-on over the years!

possibly related: #102 (from two weeks ago)

when I try to sort by "note id" or "card id" I can't reverse the sorting. I tried with Anki 2.1.35 without any other add-ons. 

To solve #102 you added the keywords "asc nulls last" to the sql commands executed, see [this commit from 10 days ago](https://github.com/hssm/advanced-browser/commit/2750144f3ef58ebcbcdf1694544ccc04715e4f20). This commit was limited to advanced_fields.py. These also seem to help in internal_fields.py. But my sql knowledge is very limited ...

For me screencasts showing a problem are useful so I made one:

![advanced_browser_cant_sort_by_nid_cid](https://user-images.githubusercontent.com/40218852/98050443-ff46e880-1e31-11eb-9c13-7c3b882f3afe.gif)

**Comment by hssm** [comment]
Thanks. I had overlooked these. I've pushed a new build that fixes this issue.
