### ISSUE TITLE
已经禁用了，还是弹出错误提示，没办法，只能删除插件。Has been disabled, or pop up an error prompt, no way, can only delete the plug-in.

### ISSUE THREAD

**Issue by kunpeng9** [hssm/advanced-browser#113]
错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-22 14:19:29

Caught exception:
Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 97, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt\browser.py", line 155, in data
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 112, in columnData
    return self.browser.customTypes[type].onData(c, n, type)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\advanced_fields.py", line 259, in cDateTimeCrt
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(c.id/1000))
OSError: [Errno 22] Invalid argument

![image](https://user-images.githubusercontent.com/44609485/107622021-282d1400-6c92-11eb-8b71-629d1d82c6b6.png)
这条笔记记录于去年，拖拉了好久没有处理，没有报告错误。This note was recorded last year. It has been delayed for a long time and no error has been reported.

**Comment by hssm** [comment]
For some reason you have a card with a strange creation time. I have changed the add-on to display `{error}` in that column instead of throwing that exception. It is up to you to fix the creation time of the card if it causes errors somewhere else.
