### ISSUE TITLE
please check your internet, HTTPS connection pool, ssl error

### ISSUE THREAD

**Issue by ShreyanshShukla31** [hssm/advanced-browser#118]
I was trying to download advanced browsing add-on. This is my first add on in this system but I am getting 
error. The error picture is attached below:-
![image](https://user-images.githubusercontent.com/79443830/111069189-f2c65100-84f1-11eb-8805-36520a418304.png)

**Comment by hssm** [comment]
Try asking for help [here](https://forums.ankiweb.net/) as this is not a problem with the add-on.
