### ISSUE TITLE
2.1.45 Alpha 1 -> add-on broken

### ISSUE THREAD

**Issue by NameLessGO** [hssm/advanced-browser#123]
![image](https://user-images.githubusercontent.com/66227691/118552515-07f77000-b72d-11eb-8e60-ea6c44db5120.png)

**When opening the "Browse"**
![image](https://user-images.githubusercontent.com/66227691/118552695-43923a00-b72d-11eb-8450-ff54e226fdc2.png)
https://www.reddit.com/r/Anki/comments/neoihx/anki_2145_alpha/ (changelogs)

**Comment by AnKingMed** [comment]
Damien said this will need an update

**Comment by AnKingMed** [comment]
@hssm just curious if you know when you'll be able to get around to making this work for 2.1.45+?  Seems like we're closer to an actual release now that we're on beta5
