### ISSUE TITLE
Collums reset position and size

### ISSUE THREAD

**Issue by Linard11** [hssm/advanced-browser#13]
I noticed that when the cursor is in one of the dialogue fields at the bottom and you close the browser window, the Collums reset their position and size.

**Comment by hssm** [comment]
- When you say cursor, do you mean the mouse or the focus of the keyboard?
- Are "dialogue fields" the text boxes or something else?
- How are you exiting the browser?
- When they reset, do they return to the previously saved state or do they start out as if they were all just added?

Any chance you can record a video? I don't understand what you're doing and I can't reproduce anything like it by trying various things.

**Comment by Linard11** [comment]
With cursor I mean the focus of the keyboard.
And with dialogue fields I mean the text boxes at the bottom of the browser where you can change the content of your cards.

I'm exiting the browser by closing the window with the X at the top right.

And as far as I could observe it, they reset always the the same order and width.

I'll try to get a record of it until tomorrow.

**Comment by hssm** [comment]
If you get a chance, try to test the add-on without any others. There is probably some other add-on that is hijacking the close event preventing this add-on from saving its columns properly.

**Comment by Linard11** [comment]
I just tested it without any other add-ons.
It still occurs.
It can also not be the problem of my PC as I just reccently build a new PC and on this new one the same bug happens.

**Comment by whiteskulleton** [comment]
Yeah. I'm having the same problem as @Linard11

**Comment by hssm** [comment]
Without a reproducible test case there isn't much I can do.

**Comment by whiteskulleton** [comment]
@hssm Are you saying that you are unable to reproduce the result? If so, something that I would add is that to get the error, a custom column added through this add-on has to be to the left of one of the default columns. In other words, add a custom column from one of the cards like "kana" or something and then move it all the way to the left. Select a card, click in a field in the note window, and then close the browser. The columns should rearrange.

Also, another suggestion to fix this would be to implement a function or something that activates the _card list_ window when the browser closes and thus doesn't mess up the columns. Just a thought.

**Comment by hssm** [comment]
Closing old issue. I'm going to assume it was a toolkit bug or Anki behaviour that is no longer present.
