### ISSUE TITLE
Search stopped working 

### ISSUE THREAD

**Issue by outlier21** [hssm/advanced-browser#14]
Hi, everything seemed to be going well since I installed advanced-browser (probably two months ago). I haven't installed any new add-ons recently. Out of the blue, this morning, I noticed that when I searched for anything, no search results were being returned (even when there were cards/notes containing the tag/word being searched for). Also, after returning a null set, the browser wouldn't show any of my cards in any of my decks. After uninstalling the add-on, the browser returned to normal and I was able to search for cards again. 

I would like to install and use the browser in the future, when this problem is fixed, bc it's great to see text as a search and a lot of the other search fields make organizing information a lot easier. Hopefully, it is resolved soon. I have a Mac, and I had no issues with the advanced-browser for the past two months (use anki regularly, for many hours) until today.

**Comment by hssm** [comment]
If you can send me a copy of your collection while it is stuck in that state I will be able to investigate the issue.

**Comment by outlier21** [comment]
​
 Outlier21AnkiCollection.apkg
<https://drive.google.com/file/d/0B6mb37YVciJ-eFVBTjNnb2x1Ukk/view?usp=drive_web>
​
Thanks. It's a large collection, fyi.

**Comment by hssm** [comment]
Unfortunately I can't reproduce the problem. Can you start Anki from the `Terminal` application and see if the console output shows any errors when using the add-on?

**Comment by hssm** [comment]
Actually, I think if you run Anki as your normally do (with the add-on) you can see the log output in the `Console` app. Sorry I'm not too familiar with Macs.

**Comment by hssm** [comment]
Start the `Console` app and see if it spits out anything for Anki when the problem is triggered and paste it here.

Otherwise you might need to run Anki from the `Terminal` app to get the output, I'm not sure.

**Comment by JustAQuest** [comment]
This is what appeared in Console, when the problem occurred. As I mentioned, no need to work on this for me. Also, I'm not a programmer, and I have no idea if this is useful:


default	11:59:03.066424 -0400	Anki	TEMP SORT TABLE PATH
default	11:59:03.066511 -0400	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, '2. WORD') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and (((n.sfld like ? escape '\' or n.flds like ? escape '\')))
default	11:59:03.106278 -0400	Anki	sql :
default	11:59:03.106380 -0400	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	11:59:03.106446 -0400	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	11:59:03.106504 -0400	Anki	collate nocase
default	11:59:03.106755 -0400	Anki	Search took: 40ms
default	11:59:04.362761 -0400	Anki	TEMP SORT TABLE PATH
default	11:59:04.362858 -0400	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, '2. WORD') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and (((n.sfld like ? escape '\' or n.flds like ? escape '\')))
default	11:59:04.381713 -0400	Anki	sql :
default	11:59:04.381827 -0400	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	11:59:04.381894 -0400	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	11:59:04.381950 -0400	Anki	collate nocase
default	11:59:04.382023 -0400	Anki	Search took: 19ms
default	11:59:06.171911 -0400	Anki	TEMP SORT TABLE PATH
default	11:59:06.172018 -0400	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, '2. WORD') from notes where id = c.nid) as srt from cards c where ((c.did in (1458657958249,1523468877468,1523027486422,1522888310863,1523027357809,1458657958258,1523468849894,1523466771002,1458657958250,1522886301631,1523466541464) or c.odid in (1458657958249,1523468877468,1523027486422,1522888310863,1523027357809,1458657958258,1523468849894,1523466771002,1458657958250,1522886301631,1523466541464)))
default	11:59:06.193057 -0400	Anki	sql :
default	11:59:06.193195 -0400	Anki	select id, srt from tmp order by tmp.srt is null, tmp.srt is '',
default	11:59:06.193262 -0400	Anki	case when tmp.srt glob '*[^0-9.]*' then tmp.srt else cast(tmp.srt AS real) end
default	11:59:06.193325 -0400	Anki	collate nocase
default	11:59:06.199416 -0400	Anki	Search took: 27ms
default	11:59:08.315506 -0400	Anki	TEMP SORT TABLE PATH
default	11:59:08.315612 -0400	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, '2. WORD') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((c.did in (1458657958249,1523468877468,1523027486422,1522888310863,1523027357809,1458657958258,1523468849894,1523466771002,1458657958250,1522886301631,1523466541464) or c.odid in (1458657958249,1523468877468,1523027486422,1522888310863,1523027357809,1458657958258,1523468849894,1523466771002,1458657958250,1522886301631,1523466541
default	11:59:08.315690 -0400	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, '2. WORD') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((c.did in (1458657958249,1523468877468,1523027486422,1522888310863,1523027357809,1458657958258,1523468849894,1523466771002,1458657958250,1522886301631,1523466541464) or c.odid in (1458657958249,1523468877468,1523027486422,1522888310863,1523027357809,1458657958258,1523468849894,1523466771002,1458657958250,1522886301631,1523466541
default	11:59:08.315768 -0400	Anki	Temp sort table sql:  create temp table tmp as select *, (select valueForField(mid, flds, '2. WORD') from notes where id = c.nid) as srt from cards c, notes n where c.nid=n.id and ((c.did in (1458657958249,1523468877468,1523027486422,1522888310863,1523027357809,1458657958258,1523468849894,1523466771002,1458657958250,1522886301631,1523466541464) or c.odid in (1458657958249,1523468877468,1523027486422,1522888310863,1523027357809,1458657958258,1523468849894,1523466771002,1458657958250,1522886301631,1523466541
