### ISSUE TITLE
 Sorting Irregularities

### ISSUE THREAD

**Issue by jolkm898np** [hssm/advanced-browser#15]
I have a document in which numbered chapters, sections, and sub-sections are separated by a period.
For example: 1.2.1, 1.2.2.

I have a deck of cards that have tags based on this convention.
When I sort by tags, the cards are sorted in an unintended way.

Could changes be made to the way the add-on sorts numbers separated by a period?

http://img.ctrlv.in/img/16/06/14/575fadd71ece6.png

**Comment by hssm** [comment]
It already sorts them correctly if they are in their own field. You should create a new field for chapter numbers so you can sort by them if you need it that badly.

There is no easy way to make it sort "correctly" when numbers are combined with other text. Any solution that does so will be really convoluted and would make sorting anything else *extremely* slow.

I personally don't want to invest any more time on this specific issue.

**Comment by jolkm898np** [comment]
I removed text tags, but still it sorts in an unusual manner.

http://img.ctrlv.in/img/16/06/17/5763dc2a223b5.png

**Comment by hssm** [comment]
The "Tags" column was still using the built-in sorting path. I just pushed a change to make it behave like all our other custom columns.

**Comment by jolkm898np** [comment]
Thanks.
If I wanted to sort using the method you mentioned, 
would I have to copy each tag into the new field, one by one, 
or is there a way to quickly move each card's tag to the field?

**Comment by hssm** [comment]
I think you can export the deck as plain text and make the changes in a spreadsheet application then re-import to update existing notes.
