### ISSUE TITLE
Port advanced-browser to 2.1

### ISSUE THREAD

**Issue by YamashitaRen** [hssm/advanced-browser#16]
Distros are starting to roll Anki 2.1 (https://www.archlinux.org/packages/community/any/anki/).
It would be nice to port the plugin to this version.

**Comment by hssm** [comment]
It has already been ported and you can get it from the github repo if you need it. I will not make a release while Anki 2.1 is still in alpha.

**Comment by YamashitaRen** [comment]
Oh, I'm sorry. That's what happens when you open issues too late :p 
Getting it from the repo is fine, thanks.
