### ISSUE TITLE
Column Idea

### ISSUE THREAD

**Issue by helloworldhello762976h9f7tb34y8t7** [hssm/advanced-browser#17]
I noticed there are capabilities to sort based on both average and total time (great btw), but I would like to also be able to sort by fastest and slowest. i.e. the card may have been answered in 5s 10s 30s 4s and 1.2s, so when sorting by fastest it would use the 1.2s and by slowest would be 30s.

**Comment by hssm** [comment]
Sorry for the delay. Both of these columns are now available in the latest version.
