### ISSUE TITLE
Couldn't use Advanced Browser after upgrade to Anki 24.06.3 on Mac - silicon. (Had to delete and reinstall addon.)

### ISSUE THREAD

**Issue by mmskeen** [hssm/advanced-browser#175]
NOTE: I deleted the add-on, and then reinstalled it. Now the add-on seems to work fine. But I thought to go ahead and report the bug. 

Here is the 'debug' information. Note that I've been using Anki 2.1.54 (with this Add-On, and others) and it's worked fine. Just today I renamed Anki to Anki 2.1.54, and then downloaded the latest Anki (24.06.3), to have both versions available on my Macbook. But I ran into this issue, forcing me to disable this add-on (until deleting and reinstalling as mentioned above). 

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 160, in _onCmd
  File "aqt.webview", line 695, in _onBridgeCmd
  File "aqt.toolbar", line 413, in _linkHandler
  File "aqt.toolbar", line 431, in _browseLinkHandler
  File "aqt.main", line 1238, in onBrowse
  File "aqt", line 146, in open
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 80, in repl
  File "aqt.browser.browser", line 145, in __init__
  File "_aqt.hooks", line 1428, in __call__
  File "/Users/michaels/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 43, in _load
    runHook("advBrowserLoaded", self)
  File "anki.hooks", line 34, in runHook
  File "/Users/michaels/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/note_fields.py", line 37, in onAdvBrowserLoad
    self.buildMappings()
  File "/Users/michaels/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/note_fields.py", line 138, in buildMappings
    self.advBrowser.setupColumns()
  File "/Users/michaels/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 95, in setupColumns
    self.table._model.columns[key] = BuiltinColumn(
ValueError: Protocol message Column has no "sorting" field.

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Add Hyperlink ['318752047', 2023-06-18T07:39, 'None', '']
Additional Card Fields Fork for 21 ['744725736', 2022-10-23T06:10, 'None', mod]
Advanced Browser ['874215009', 2023-10-21T10:34, 'None', mod]
Advanced Card Styles ['1625103157', 2021-12-28T12:49, 'None', '']
Advanced Review Bottom Bar ['1136455830', 2024-08-22T07:04, 'None', '']
AnKing Note Types Easy Customization ['952691989', 2024-08-19T04:41, 'None', mod]
Anki Palace Butler ['butler', 2022-08-17T21:23, 'None', mod]
Anki Simulator ['817108664', 2023-11-06T12:26, 'None', '']
Batch Editing ['291119185', 2023-10-25T20:38, 'None', '']
Browser Resizer ['1435775540', 2023-11-11T12:16, 'None', mod]
Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T17:11, 'None', mod]
Clickable Tags v20 ['1739176371', 2022-01-30T17:58, 'None', '']
Closet For Anki ['272311064', 2022-08-12T04:27, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-02-29T20:22, 'v0.9.2-beta', mod]
Custom Background Image and Gear Icon ['1210908941', 2023-04-18T21:19, 'None', mod]
Customize Keyboard Shortcuts ['24411424', 2023-11-01T05:17, 'None', mod]
Edit Field During Review Cloze ['385888438', 2024-01-03T02:19, '6.18', mod]
Export Single Tag For Sharing ['960563361', 2022-04-10T17:30, 'None', '']
Extended Tag AddEdit Dialog ['1135507717', 2023-11-11T11:58, 'None', mod]
Fastbar- with nightmode support ['46611790', 2023-06-27T07:47, 'None', '']
Google Doc Decks Remote Decks ['924929499', 2024-05-04T21:58, 'None', mod]
Google Translate ['1536291224', 2024-09-20T17:05, 'None', '']
High Yield Tags ['1918380616', 2023-01-10T14:14, 'None', mod]
Hint Hotkeys ['1844908621', 2023-04-14T10:13, 'None', '']
Image Editor ['307397307', 2022-09-08T00:09, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T03:15, 'None', '']
More Decks Stats and Time Left ['1556734708', 2024-08-19T18:49, 'None', mod]
More Overview Stats 21 ['738807903', 2024-08-22T05:14, 'None', mod]
Quick Colour Changing ['2491935955', 2023-10-18T23:15, 'None', mod]
Reset Ease ['947935257', 2023-11-11T20:22, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
Special Fields ['1102281552', 2024-03-19T19:34, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T06:24, 'None', mod]
Straight Reward ['957961234', 2023-11-01T10:11, 'None', '']
Symbols As You Type ['2040501954', 2024-01-20T00:42, 'None', '']
Symbols ['1461102936', 2024-02-10T11:53, 'None', mod]
Web Browser - Search terms Import texts and images automatically ['864545277', 2023-11-17T14:28, 'None', mod]
Wrapper meta-addon ['396502676', 2024-06-10T06:00, 'None', '']
add-on dialog searchfilter bar ['561945101', 2023-10-18T12:22, 'None', '']
memrise2anki ['memrise2anki', 0, 'None', '']
rebuildempty some or all filtered decks ['104518886', 2023-05-16T18:33, 'None', '']

===IDs of active AnkiWeb add-ons===
104518886 1046608507 1102281552 1135507717 1136455830 1210908941 1374772155 1435775540 1461102936 1536291224 1556734708 1625103157 1739176371 1771074083 1844908621 1898790263 1918380616 2040501954 24411424 2491935955 272311064 291119185 307397307 318752047 385888438 396502676 46611790 561945101 738807903 744725736 817108664 831846358 864545277 874215009 924929499 947935257 952691989 957961234 960563361

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
BetterSearch ['1052724801', 2024-03-06T11:25, 'None', mod]
Extended Card Stats During Review ['1008566916', 2024-02-26T14:07, 'None', '']
Free Weekend - or Any Other Day ['742185195', 2020-04-10T07:57, 'None', mod]
Highlight Search Results in the Browser ['225180905', 2023-10-21T15:17, 'None', '']
Load Balanced Scheduler ['208879074', 2019-07-23T22:37, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T14:00, 'None', '']
Pop-up Dictionary ['popup_dictionary', 2021-08-04T18:30, 'None', mod]
Progress Bar ['2091361802', 2019-03-02T21:27, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T07:59, 'None', '']
Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2022-08-15T03:22, 'None', '']
Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T14:52, 'None', mod]
Syntax Highlighting for Code ['1463041493', 2018-10-06T21:31, 'None', '']
The KING of Button Add-ons ['374005964', 2024-09-23T08:14, 'None', '']

**Comment by DoctorToBeIn23** [comment]
I can confirm this requires deleting and then redownloading addon.

**Comment by abdnh** [comment]
I've seen this reported a few times. It's a confusing error that's probably caused by an update error (maybe something in Anki). I don't think it's something we can fix in the add-on.

**Comment by ijgnd** [comment]
actually we caused this problem and can fix it (probably):

the version uploaded to 
https://ankiweb.net/shared/info/874215009 on 2023-10-21 for 23.10+ has broken metadata.

The branch_index is the same as in the prior version, the uploaded version misses this fix: https://github.com/AnKing-VIP/advanced-browser/commit/aafa77d88ed1a9707924360f2231abab58a9eb5b

Someone from the anking team needs to upload a fixed version to ankiweb.

I think this version should include everything thats needed: https://github.com/AnKing-VIP/advanced-browser/releases/tag/v4.4

but maybe @ DoctorToBeIn23 could check this .ankiaddon file before it's distributed widely. I don't have time for this at the moment.

**Comment by abdnh** [comment]
Thanks @ijgnd! Just pushed the fixed version to AnkiWeb.

**Comment by ijgnd** [comment]
I'm not sure about this. But at least the newer version shouldn't hurt.
