### ISSUE TITLE
What does the column "% of lvl" mean?

### ISSUE THREAD

**Issue by nstjhp** [hssm/advanced-browser#178]
Nice add-on - thank you! I saw some very useful things. 
But as the title asks: What does the column "% of lvl" mean? And how is it calculated?

**Comment by ijgnd** [comment]
https://github.com/AnKing-VIP/advanced-browser/blob/61146839aa823d13df7e3f7d540beb8921702feb/advancedbrowser/advancedbrowser/advanced_fields.py#L170

-> https://github.com/AnKing-VIP/advanced-browser/blob/61146839aa823d13df7e3f7d540beb8921702feb/advancedbrowser/advancedbrowser/advanced_fields.py#L412

check lines 421-423

**Comment by nstjhp** [comment]
Ah thanks, I was reading it as level not interval. Now I understand it's how far through the interval it is so it will change daily for my cards, with higher %s meaning it will probably be seen soon.
