### ISSUE TITLE
Column Addition: Percent Correct

### ISSUE THREAD

**Issue by alexalperov** [hssm/advanced-browser#21]
A new column that is Lapses/Total Reviews. This would allow users to sort/filter cards that have low percentages. Sorting by most lapses can be misleading because cards that have been in the deck longer will have more lapses even if they aren't "problem cards".

**Comment by alexalperov** [comment]
Here is a rough sketch of what it could be. I am not sure how to sort it. 
`       def cPctCorrect(c, n, t):
            responsesFunc =  mw.col.db.scalar(
                "select reps from cards where id = ?", c.id)

            lapsesFunc = mw.col.db.scalar(
                "select lapses from cards where id = ?", c.id)

            if responsesFunc > 0:
                percent = Decimal(lapsesFunc)/Decimal(responsesFunc)
            if responsesFunc:
                return str(percent)

        cc = advBrowser.newCustomColumn(
            type='cpct',
            name='Percent Correct',
            onData=cPctCorrect,
            onSort=lambda: "(select max(percent))"
        )
        self.customColumns.append(cc)`

**Comment by hssm** [comment]
Try this:

```
        # Percent correct
        def cPctCorrect(c, n, t):
            if c.reps > 0:
                return "{:2.0f}%".format(
                    100 - ((c.lapses / float(c.reps)) * 100))
            return "0%"

        cc = advBrowser.newCustomColumn(
            type = 'cpct',
            name = 'Percent Correct',
            onData = cPctCorrect,
            onSort = lambda: "cast(c.lapses as real)/c.reps"
        )
        self.customColumns.append(cc)
```

If you're okay with this I will add it to the next release.

**Comment by alexalperov** [comment]
Just ran it and it looks good with me.

**Comment by hssm** [comment]
The column is now in the released version on AnkiWeb.

Modifying search queries is not possible through this add-on, sorry.
