### ISSUE TITLE
Search returns NULL with multiple strings OR search

### ISSUE THREAD

**Issue by markjulie** [hssm/advanced-browser#24]
I am working with a deck of Hebrew words which I created from Basic/Reversed. I can launch Anki.app on my Mac and search deck:current or deck:MidHeb and see all cards. If I modify to 'deck:MidHeb dog' I get 'dog' as the card showing as expected. Also, if I search 'deck:MidHeb (dog or cat or mouse), Anki returns those words or longer words containing those strings as I expect. When I add a fourth or fifth term to my OR string, the search function stops returning any values. Furthermore, going back to deck:MidHeb or another successful recent search returnes NULL values until I restart Anki. Suggestions? (I have had longer OR strings work previously on this deck). I have also run Check Database several times between restarts. 

This is excerpted from TenderApp and Damien. The error goes away when I boot Anki with addons disabled. Any suggestions or known limitations?

Mark

**Comment by hssm** [comment]
I can't reproduce it, so you will have to send me a copy of your collection and an example search string that breaks it.

Also make sure you are you using the latest version of the add-on.

**Comment by markjulie** [comment]
Houssam,

Download the shared deck for Brandeis Modern Hebrew ©2005, and search 
'deck:"Brandeis Modern Hebrew" (red or green or blue or yellow or black 
or white)'. My Anki version and add-on were current as of last weekend. 
Searching the deck alone worked. Searching one or two OR items worked. 
More than three definitely crashed/froze any further searching until an 
Anki restart.

Blessings and thanks,
Mark

**Comment by hssm** [comment]
I can't reproduce it with that either. It sounds like it's the same problem as https://github.com/hssm/advanced-browser/issues/14 which is limited to Macs. I don't have a Mac available so I can't test it or reproduce it. Sorry.

There is a very small chance the problem will go away with newer releases of the Anki libraries. If you are interested, you can try getting a [beta release of Anki 2.1](https://apps.ankiweb.net/docs/beta.html) and using the Advanced Browser add-on on the `master` branch here which was updated to support it.

**Comment by markjulie** [comment]
Houssam,

I downloaded Beta4 and unzipped the github dmg to the Anki Addons 
folder. I am not sure if it should go into /addons or /addons21. Also, 
it does not perform at all currently which tells me I have not installed 
correctly. If I understand correctly, 874215009 is a version not 
necessarily compatible with Anki2.1, right?

If you have time to quickly give me the correct addon install steps, I 
will do it. That is beyond the scope of my original question.

Blessings,
Mark

**Comment by markjulie** [comment]
Further update: I installed the addon on Windows 7 on my wife's computer 
and could not reproduce the behavior, so it must be a Mac issue. Thanks 
for troubleshooting.

Blessings,
Mark

**Comment by hssm** [comment]
Sorry for being sparse on details. You will need to [download the add-on's code from the master branch](https://github.com/hssm/advanced-browser/archive/master.zip) and extract the `advancedbrowser` folder into your `addons21` directory like this:

![image](https://user-images.githubusercontent.com/789082/28639566-03d0d398-728c-11e7-96f3-d8b72164d626.png)

(copy right folder into left folder)

If the issue remains even with the beta version you can try to find the log output of the application. The add-on prints a diagnostic message when searches fail (thanks to a previous Mac-only issue) which could prove useful. Again, I'm not too familiar with Macs or how to get this log output, but I believe some combination of running Anki through the `Terminal` and/or the `Console` apps would yield some results.

**Comment by hssm** [comment]
It was actually the same issue as #14 which has been fixed for a while.
