### ISSUE TITLE
Sort(click on column header) not working for custom fields using Unicode

### ISSUE THREAD

**Issue by theGivingTree** [hssm/advanced-browser#25]
Clicking on the column header shows nothing at all (as if no cards exist).
When I modify the name of the custom field using only ascii, it works.

**Comment by hssm** [comment]
Seems to work for me. Can you please make sure you are using the latest version of the add-on? Otherwise I'll need an example or a sample collection.

**Comment by theGivingTree** [comment]
I updated it, but the issue was same.
Here is the [link](https://youtu.be/9znm2bH6QWg) for the bug reproduce

**Comment by kashimotoxiang** [comment]
Same problem. It seems like that this add-on only has this problem on Macbook but works well on PC.

**Comment by linonetwo** [comment]
In Macbook, Anki2.1.
Can't sort field, if the field name is in CJK(Chinese Japanese Koren).

**Comment by linonetwo** [comment]
Maybe you need to handle CJK unicode here?

https://github.com/hssm/advanced-browser/blob/e0da46ffb63452431a592d27002854f64af4379b/advancedbrowser/advancedbrowser/note_fields.py#L40

**Comment by hssm** [comment]
That line ends up generating SQL that looks like this:
`create temp table tmp as select *, (select valueForField(mid, flds, '意味') from notes where id = c.nid)...`

I don't think it is the source of the problem. It's printed in the console output so you can verify this for yourself if you'd like to try. I wonder what it looks like on your end, and why this issue only seems to happen on Macs.

My suspicion is that the issue is most likely happening on the following lines and is being silently ignored:
https://github.com/hssm/advanced-browser/blob/e0da46ffb63452431a592d27002854f64af4379b/advancedbrowser/advancedbrowser/note_fields.py#L99-L100

I've already put in an elaborate workaround for a Mac-only issue where there is a mismatch with the model ID (the `mid` in this function) stored in the configuration and the model ID that the database engine gives back, but it's possible there are more cases related to this behaviour that I haven't handled.

I'd be very grateful if you are able to debug this issue. It's been around for a while and I don't have the right equipment to look into it myself.

**Comment by linonetwo** [comment]
How to debug it?
I've only developed electron application, where I can open developer tool and see the log.

While I tried:
```python
index = self.modelFieldPos.get(mid).get(fldName, None)
            print(fldName)
```
There is no a developer tool to see the output.

**Comment by hssm** [comment]
Other platforms work correctly, yes. It is possible the SQLite version on Mac is normalizing or escaping the text in some way. Or it could be the python layer in between, I really don't know.

I'm not sure if the method you tried works properly (for me it just throws an exception when trying to print things out like that). Instead, I have pushed a debug version of the file `note_fields.py` that you can grab [from here](https://github.com/hssm/advanced-browser/blob/2591d7ccaa25f5f7dd250b441852499a267c4cae/note_fields.py). It will write the debug output to a file.

Please follow these steps:
1 - replace `note_fields.py` with the version above
2 - start Anki and open a browser
3 - try a search and sort with a column that works
4 - try a search and sort with a column that does not work
5 - close anki completely
6 - there will be a file named `debug.txt` inside the add-on directory that you can send me to look at

**Comment by linonetwo** [comment]
Oh, when clicking on browser:

```
advancedbrowser/note_fields.py", line 78, in buildMappings
    print(pprint.pformat(self.modelFieldPos, indent=4))
<class 'UnicodeEncodeError'>: 'ascii' codec can't encode characters in position 59-66: ordinal not in range(128)
```

**Comment by linonetwo** [comment]
[debug.txt](https://github.com/hssm/advanced-browser/files/2896951/debug.txt)
Here you are.

**Comment by hssm** [comment]
Can you try adding these lines:
```
            if fldName == "中文":
                print(mid)
```

above [this one](https://github.com/hssm/advanced-browser/blob/2591d7ccaa25f5f7dd250b441852499a267c4cae/note_fields.py#L120) and search and sort by "中文" then give me the results again.

**Comment by linonetwo** [comment]
[debug.txt](https://github.com/hssm/advanced-browser/files/2896997/debug.txt)

I added
```python
        try:
            index = self.modelFieldPos.get(mid).get(fldName, None)
            if fldName == "中文":
                print("if fldName == \"中文\":")
                print(mid)
```

**Comment by linonetwo** [comment]
Oh, you updated your code? It works!
Now it can sort Chinese field if I'm use code from https://github.com/hssm/advanced-browser/blob/2591d7ccaa25f5f7dd250b441852499a267c4cae/note_fields.py

**Comment by hssm** [comment]
I didn't make any changes to the code. What version of the add-on do you have installed? What version of Anki?

The debug.txt from above - did the sort work correctly when you generated it or not?

**Comment by linonetwo** [comment]
I went to sleep.

I'm using Anki 2.1.8 (71e0c880)Qt 5.12.0 PyQt 5.11.3

For AdvancedBrowser, I tried redownload addon from ankiweb, this version don't work.
Then replace with code from [/note_fields.py@`2591d7c`](https://github.com/hssm/advanced-browser/blob/2591d7ccaa25f5f7dd250b441852499a267c4cae/note_fields.py), and change Line 12 to be

```python
sys.stdout = open(dir_path + '/debug.txt', 'w', encoding='utf-8')
```
It just works.

**Comment by hssm** [comment]
Interesting. Maybe the problem all along was printing logs to the console.

Can you restore the add-on to the downloaded version and try removing all the `print` lines from `core.py` and `note_fields.py` and see what happens?

**Comment by linonetwo** [comment]
No, change line 116 to 

```python
        except Exception as ex:
            pass
```
still can't sort.

**Comment by linonetwo** [comment]
So maybe you need to set sedout encoding to utf-8, or just comment out those print() on production?

**Comment by hssm** [comment]
I have commented out the lines for now. In the future I may make them configurable for debug builds.

Thank you very much for your patience and help with figuring this one out. Much appreciated. I've pushed a new version to AnkiWeb that has a fix now.
