### ISSUE TITLE
Sorting of tags broken

### ISSUE THREAD

**Issue by rathsky** [hssm/advanced-browser#28]
I'm not sure if tag sorting is still a thing – your github page doesn't carry the "(sortable)" as the Ankiweb page does – anyhow, for me it's broken. My cards have nothing but a simple two digit tag:

![](http://i.imgur.com/ZXubg7Y.png)

Anki 2.0.47, Advanced Browser 1.5.3

Nonetheless, thanks so much for your work.

**Comment by basiscape25** [comment]
I agree that I am also experiencing this issue in that the cards do not sort by tag. It actually seems to sort by due date for me

**Comment by hssm** [comment]
I've fixed this issue and published a new version on AnkiWeb, although I am only supporting Anki 2.1+ from here on so it is only available for that version.
