### ISSUE TITLE
Anki 2.1.0beta14 doesn't start if advanced-browser is installed

### ISSUE THREAD

**Issue by YamashitaRen** [hssm/advanced-browser#29]
Since I updated Anki 2.1 from beta12 to beta14, I can't start it anymore if advanced-browser is in my plugin directory.

I guess you have to update the plugin to whatever they changed in Anki...

**Comment by hssm** [comment]
This is now fixed and a version compatible with Anki 2.1 is published on AnkiWeb, so you can download it straight from the application with the add-on code.

**Comment by YamashitaRen** [comment]
Thanks but unfortunately I get an issue with Anki 2.1.0beta20 :/
`Un greffon que vous avez installé n'a pu se charger. Si le problème persiste, allez dans le menu Outils>Greffons et désactivez ou supprimez ce greffon.

Au chargement de 'Advanced Browser':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 57, in loadAddons
    __import__(dir)
  File "/home/myuser/.local/share/Anki2/addons21/874215009/__init__.py", line 6, in <module>
    from core import AdvancedBrowser
ModuleNotFoundError: No module named 'core'`

**Comment by hssm** [comment]
I've uploaded an update that should fix it. Thanks for the feedback.

It wasn't happening when running Anki from source so I didn't catch it the first time around.

**Comment by YamashitaRen** [comment]
Seems good, thanks :)
