### ISSUE TITLE
Right click on column names after adding new field to note

### ISSUE THREAD

**Issue by DanielBiskup** [hssm/advanced-browser#30]
![bugadvancedbrowser2](https://user-images.githubusercontent.com/1309272/30516856-e46eb906-9b4a-11e7-892a-6b684c191dfc.png)

This happened, because I just added a new field to the note type. After restarting Anki, everything is back to normal, so it’s not a critical bug.
The behaviour is reproduceable:
1) Add a new field to the note type.
2) Right click on the column names of the browser.

P.S.:
Ideas on what you could add to the Plug-In:
In the browser allow a field to be interpreted as containing numbers, so I don’t have to fill my “page” field with (001, 012, 123) but can just use (1, 12, 123).
When adding a new note to, it does not show up in the browser immediately. One has to close the browser and open it again for the appear in the browser. Maybe you can do something about that?

Thank you very much for your Plug-In.

**Comment by hssm** [comment]
This is fixed in the latest version.
