### ISSUE TITLE
Sort(click on column header) not working when field contains only number or an image

### ISSUE THREAD

**Issue by guischmo** [hssm/advanced-browser#34]
**PROBLEM 1)** I have a column with only numbers, when i try to sort it everything goes blank

_here we see the colum "Numéro", but the sorting is on antother column so everything works_
![screen shot 2018-06-12 at 12 08 41](https://user-images.githubusercontent.com/28254131/41286299-3e7d1e70-6e3f-11e8-927a-29045910f76e.jpg)

_here is what happens when i try to sort by "Numéro"_
![screen shot 2018-06-12 at 12 08 48](https://user-images.githubusercontent.com/28254131/41286303-3fe158a8-6e3f-11e8-9858-311273246cd7.jpg)

**PROBLEM 2)** I have a column with only pictures, is it normal that they don't appear as "picture1.jpg" in the sorting colum ? Instead it is just blank

_Here we can see that despite having a picture in my "Image" field, i dont see "picture.jpg" in the image colum_
![screen shot 2018-06-12 at 12 08 27](https://user-images.githubusercontent.com/28254131/41286295-3bf836b2-6e3f-11e8-9cba-9a9ab5830a4c.jpg)

**Comment by hssm** [comment]
1 - If you are on a Mac, then it seems to be another case of https://github.com/hssm/advanced-browser/issues/14. It's been really hard to track this down as I don't have any Mac devices myself to investigate.

2 - I can fix this one.

**Comment by hssm** [comment]
Latest release on AnkiWeb fixes 2.

**Comment by guischmo** [comment]
For 1) I found the problem.  It's because the field name contain french accent.

When i name the field "numero" instead of "numéro", everything works :)
