### ISSUE TITLE
Shortcut to toggle note-only view doesn't work

### ISSUE THREAD

**Issue by metronidazole** [hssm/advanced-browser#36]
I'm using Anki 2.1 and the shortcut to toggle note-only view (ctrl+shift+n) doesn't work. If i have the card browser in focus, and any card selected, pressing the shortcut only deselects the card and doesn't enable the note-only view.

If I manually toggle the function and try again, the same thing occurs.

**Comment by hssm** [comment]
I've published a new version on ankiweb with a fix for this.
