### ISSUE TITLE
browser RTL column: parentheses incorrectly displayed

### ISSUE THREAD

**Issue by grac-zh** [hssm/advanced-browser#37]
as i have reported to ANKI the display of parentheses in a RLT column is incorrect.
after upgrading ANKI to version 2.1 and updating your addon i realised, that it's still the same.
since ANKI has fixed the problem (without the addon), the error has to be in your addon.

see my thread in ANKIWEB, beginning 30 of july 2018:

https://anki.tenderapp.com/discussions/ankidesktop/29016-browser-ltr-column-parentheses-incorrectly-displayed 

thanks for fixing this annoying problem.
and thanks for your very useful addon which i use daily

stephan, switzerland

PS. damien (ANKI support) asked me to add the following link in order to solve this problem easier:

https://github.com/dae/anki/commit/0acf9b38a4b42e4d59afcb3e9e4564707cd80560

**Comment by hssm** [comment]
Thanks for letting me know. I've published a new version on ankiweb with a fix.
