### ISSUE TITLE
scrollbar doesn't touch window edge

### ISSUE THREAD

**Issue by omega3** [hssm/advanced-browser#38]
I use night-mode add on. I made scrollbar wider but it is somehow moved to the left, it doesn't touch window border:
https://i.imgur.com/0s0moZ3.png
I marked in red.
Also in maximised window.
https://i.imgur.com/fVu82Yx.png
When I use mouse scroll this is not very important but when I need to click on scrollbar to move it when database have lots of entries it becomes a problem because I have to always check if mouse pointer is places directly over scrollbar. If there was no such space I could just move mouse to the right screen edge and scroll down.

This is in advanced browser mode. In review mode scrollbar touches window border.

Can this be set in this add-on or it is hard-coded in Anki or has something to do with advanced browser?

Damien wrote:
> Having the scrollbar touch the side of the screen would not look good on some systems. It behaves differently in the review area because that is a single window, not a combination of widgets.

https://anki.tenderapp.com/discussions/ankidesktop/29765-anki-21-look-on-plasma-5

This is on:
Anki Version 2.1.4, Qt 5.9.2 PyQt 5.9 on Manjaro Linux Plasma 5.13.5, QT 5.11.1
Night Mode 2.1.9

**Comment by omega3** [comment]
>  It is going to look ugly and will differ across platforms

Well, you could let user modify it in add-on configuration file and leave default value as is now (on the above screenshot). 

> I'd accept a pull request that implements it.

I am not a programmer, so I am not able to do that.

**Comment by hssm** [comment]
Closing as not really an issue.
