### ISSUE TITLE
sidebar doesn't keep width

### ISSUE THREAD

**Issue by omega3** [hssm/advanced-browser#39]
Every time I open anki and switch to browser view sidebar gets back to the same position:
https://i.imgur.com/hDWXTIe.png

Anki Version 2.1.4, Qt 5.9.2 PyQt 5.9 on Manjaro Linux Plasma 5.13.5, QT 5.11.1
Night Mode 2.1.9

advanced browser version - the newest - I keep them updated

**Comment by hssm** [comment]
As far as I understand this has nothing to do with the Advanced Browser add-on. It doesn't modify the sidebar in any way.

**Comment by omega3** [comment]
Well then how can I identify the source of this behaviour? I disabled night-mode add-on and it is still the same. 
Did you checked on installed version of anki or not installed (run from bin file)?

**Comment by omega3** [comment]
I close it. It is invalid because it most probably is caused by Night mode "Enable in Dialogs" option.
