### ISSUE TITLE
Anki "Advanced Browser" Notes Date & Time of creation feature request

### ISSUE THREAD

**Issue by cr7mmsa** [hssm/advanced-browser#45]
Can you please add "creation time" of note feature, because in the normal browser only by the date of creation we can sort them, so can you please add a feature to sort the cards by date&time of creation not only by the date of creation.. i need this alot and thanks again

**Comment by hssm** [comment]
I've uploaded a new version on AnkiWeb that has a new column under the `- Advanced -` menu named `Created` that will show you the full timestamp. Hope that helps.

**Comment by cr7mmsa** [comment]
This fixed all my problems thanks alot, u are a great man
