### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by agentjsp** [hssm/advanced-browser#46]
![advbrowser](https://user-images.githubusercontent.com/38056528/53782780-b0f67f00-3ec3-11e9-8492-4d973de4b15e.PNG)
The add-on doesn't seem to work for me with Anki 2.1.9 and version 2.5. The form control where you can adjust the number of columns never shows up in the bottom right.

**Comment by hssm** [comment]
[Different add-on](https://ankiweb.net/shared/info/3491767031)

**Comment by agentjsp** [comment]
Oh, thanks. That had confused.
