### ISSUE TITLE
Text not showing properly

### ISSUE THREAD

**Issue by vintotal** [hssm/advanced-browser#47]
When I sort notes by field, the content of some lines cannot be read. Please look at the attached screen captures. Only fields with spaces in them look to be affected. Merci!
![presse-papier01](https://user-images.githubusercontent.com/1743914/53819115-4848ea00-3f37-11e9-9c0a-b83d975576fe.jpg)
![2](https://user-images.githubusercontent.com/1743914/53819246-8fcf7600-3f37-11e9-8634-dc89b6ee7012.jpg)

**Comment by hssm** [comment]
Can you please export that deck and send it to me?

**Comment by vintotal** [comment]
It is a bit big, but here it is. Password is anki.
[deck.zip](https://github.com/hssm/advanced-browser/files/2936078/deck.zip)

**Comment by hssm** [comment]
Thanks. I've uploaded a fix.

**Comment by vintotal** [comment]
Thank you for your quick fix and work. Apparently the text is still off in some cases. Please consult the attached image. The deck is the same as the one provided in my last post. I am using Anki 2.0.52. Is it an Anki 2.0 specific issue?
![presse-papier01](https://user-images.githubusercontent.com/1743914/53886321-c36cd780-3fed-11e9-8604-8049557c8d63.jpg)

**Comment by hssm** [comment]
Yes, the add-on is no longer updated for Anki 2.0. The fix is [a tiny change](https://github.com/hssm/advanced-browser/commit/3fd386ac8fe0275c1dce06164a6323d71c6d0be2), however, and you can change it for your local copy of the add-on if you intend to keep using Anki 2.0.
