### ISSUE TITLE
make shortcut for one-row-mode ("Ctrl+Alt+N") user configurable

### ISSUE THREAD

**Issue by ijgnd** [hssm/advanced-browser#48]
The addition of "Note browser mode (show a single card per note type)" was a great addition and makes the browser much more useful. 

The  hardcoded shortcut has a drawback for some languages: In Polish you need the combo AltGr+N to type a special character that Polish uses. If you press AltGr+N with the advanced browser you won't get the Polish special character but the view of the table is toggled.

This was reported at reddit multiple times: 

- 2019-03-12 https://www.reddit.com/r/Anki/comments/azzhpw/what_does_altgrn_do_in_the_browser/
- 2019-05-12 https://www.reddit.com/r/Anki/comments/bnp8eb/polish_characters_in_anki/

Thanks for creating this essential add-on !

**Comment by galantra** [comment]
I second this also for others uses than Polish.

To others who face the problem: Does [this add-on](https://ankiweb.net/shared/info/1786482670) help? (I'm not sure. Myself I use switch from my default German keyboard to Polish 214, which is very similar)

**Comment by hssm** [comment]
I've uploaded a new version that makes the shortcut configurable. Use the config editor in Anki's add-on manager to change it to whatever you prefer.
