### ISSUE TITLE
/advancedbrowser/config.py, line 33: AttributeError: 'AddonManager' object has no attribute 'setConfigUpdatedAction'

### ISSUE THREAD

**Issue by ola-sk** [hssm/advanced-browser#54]
I get this message when I first run Anki Version 2.1.0beta36. Closing the message and opening Anki again causes no visible window to pop up. It doesn't open.
Message:

> An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
> 
> When loading 'Advanced Browser':

```
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 57, in loadAddons
    __import__(dir)
  File "/home/ola/.local/share/Anki2/addons21/874215009/__init__.py", line 6, in <module>
    from . import advancedbrowser
  File "/home/ola/.local/share/Anki2/addons21/874215009/advancedbrowser/__init__.py", line 5, in <module>
    from . import note_fields
  File "/home/ola/.local/share/Anki2/addons21/874215009/advancedbrowser/note_fields.py", line 8, in <module>
    from .config import getEachFieldInSingleList
  File "/home/ola/.local/share/Anki2/addons21/874215009/advancedbrowser/config.py", line 33, in <module>
    mw.addonManager.setConfigUpdatedAction(__name__,update)
AttributeError: 'AddonManager' object has no attribute 'setConfigUpdatedAction'
```

**Content of the '/home/ola/.local/share/Anki2/addons21/874215009/advancedbrowser/config.py'.**
```
import aqt
from aqt import mw
from .internal_fields import iff
from anki.hooks import addHook, remHook


singleList = False
userOption = None
def getUserOption():
    global userOption
    if userOption is None:
        userOption = aqt.mw.addonManager.getConfig(__name__)
    return userOption

def getEachFieldInSingleList():
    return getUserOption().get("Use a single list for fields", False)

def getUseInternalFields():
    return getUserOption().get("Show internal fields", False)

def update(_):
    global userOption
    userOption = None
    processInternal()


def processInternal():
    fn = addHook if getUseInternalFields() else remHook
    fn("advBrowserLoaded", iff.onAdvBrowserLoad)
    fn("advBrowserBuildContext", iff.onBuildContextMenu)
processInternal()

mw.addonManager.setConfigUpdatedAction(__name__,update)
```

**Comment by Ola-Sok** [comment]
Commenting out the line that causes the AttributeError in the file at the end of a traceback message gets Anki to run, and the -Advanced- options to show up in the Browser, but I don't know what implications removing the line of code has.

**Comment by hssm** [comment]
The add-on may still have issues after commenting out that line.

It seems that Ubuntu 18.04 ships with an older version of Anki which does not have the "add-on manager" component which this add-on now relies on. There may be an older release that is compatible, though.

The add-on targets the most recent stable release of Anki and I'm afraid making changes to support older versions isn't something I have time for.
