### ISSUE TITLE
Doesn't work? Or can't figure out how to let it work.

### ISSUE THREAD

**Issue by M-Azuma** [hssm/advanced-browser#57]
Hi. Today it's my first time to try this plugin. I installed and restarted, but my deck browser is still the same as before.

I have restarted Anki multiple times and tried to disable all other plugins, but it isn't solved. What I am missing?

My version is below and on Windows 10.
```
Version 2.1.14 (7b93e985)
Qt 5.12.1 PyQt 5.11.3
```

**Comment by hssm** [comment]
You need to right-click the title of a column (like [at the top](https://camo.githubusercontent.com/3f4bfaefb22b5254bc4fe6f6cf95a59c5e432b9b/68747470733a2f2f7261772e6769746875622e636f6d2f6873736d2f616476616e6365642d62726f777365722f6d61737465722f646f63732f73637265656e73686f745f696e666f2e706e67) where there is Card or Due) to see the new entries.

**Comment by M-Azuma** [comment]
Thank you! It is I misunderstood the feature of the plugin. Though, I would also like to have more columns. 

May I ask you what plugin brings these buttons?
![image](https://user-images.githubusercontent.com/3676278/70318181-6d69e080-185a-11ea-939a-1b31ce771c51.png)

**Comment by hssm** [comment]
It might be [this one](https://ankiweb.net/shared/info/1955978390), but I'm not sure.
