### ISSUE TITLE
Error dump when clicking on a collection in the browser

### ISSUE THREAD

**Issue by LesLandau** [hssm/advanced-browser#59]
Hi,

I am using ANKI desktop Version 2.1.12 (eef86bf3) on Windows 10. With the addon disabled I do not get this error.
With the addon enabled, when I go to the browser and click on a particular collection I get an error with a dump below. It is the only deck to do this and that deck is very similar to others.

I have no idea what any of this dump means.
Regards,
Les

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.12 (eef86bf3) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\progress.py", line 72, in handler
  File "aqt\browser.py", line 595, in _onSearchActivated
  File "aqt\browser.py", line 606, in search
  File "C:\Users\LesL\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 123, in search
    nid = card.nid
<class 'AttributeError'>: 'Card' object has no attribute 'nid'

**Comment by hssm** [comment]
Would you be able to send me a copy of your collection (not deck) so I can try to reproduce it? You can export it from the main menu.

**Comment by LesLandau** [comment]
Hi,

I can do that, but it will be very big as I have many videos. I’m not sure if there is a size limit, but I will try.

Cheers,
Les

**Comment by LesLandau** [comment]
[collection-2020-02-08@08-43-31.zip](https://github.com/hssm/advanced-browser/files/4173105/collection-2020-02-08%4008-43-31.zip)
OK, so here is the file. The deck that has the problem is Auslan_Part1 and also NSW1, but other decks are OK.
![Error](https://user-images.githubusercontent.com/60770354/74069557-b56fd400-4a52-11ea-8bf9-f7fd12ac64ee.jpg)
![Error](https://user-images.githubusercontent.com/60770354/74069569-c3255980-4a52-11ea-8fb2-5b468b60473a.jpg)

**Comment by hssm** [comment]
The issue is caused by a single card in your collection that has an ID of `0` which is not valid. Perhaps another add-on has modified it.

You will need to remove this card and make a new one. It's quite likely that it will cause other issues if it remains in your collection.

![image](https://user-images.githubusercontent.com/789082/74082516-e41b9800-4aae-11ea-8873-4b6e2034c8d2.png)
