### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Arthur-Milchior** [hssm/advanced-browser#71]
Hi,

I realized there is no License in this repo. Since we are only three contributor, I assume it won't really be a problem to ensure that every one agrees. (For this reason I ping @gnprice )

Given that the add-on interacts with anki, under AGPLv3, I assume it means that the add-on should be under AGPLv3 or GPLv3, so there is not a lot of choice anyway.
I'd have a strong preference for GPLv3. Since your add-on does not directly interact with anything on the network, it should not make any difference for you. 

The reason for this issue is that I'll start a job soon as a dev', and the company restrict what I can contribute to, even on personal time. And I can only send PR to repos which have some specific licenses. GPL* is allowed, not AGPL*. So if you choose AGPL or if you don't add license I will not be able to contribute anymore. I hope my contributions were useful and that this can be sorted out so that I can still improve your wonderful add-on

**Comment by hssm** [comment]
Hi Arthur,

Firstly, congratulations on your new job. I hope it works out well for you.

>the company restrict what I can contribute to, even on personal time

This seems like a bizarre practice, and it's a shame that companies still try to lay claim your personal time in our industry. It's not unusual to amend contracts until both sides agree to it, so if it's not too late and you're in a position to do so, it wouldn't hurt to try to get this changed before agreeing to it. It might not even be legal in your country. (There was a [recent Hacker News thread](https://news.ycombinator.com/item?id=21823413) about a similar practice you might find relevant).

Anyway, this add-on has always been licensed under GPLv3 with a slight mention of it in the readme. I've gone ahead and added a license file to reflect it.

**Comment by Arthur-Milchior** [comment]
Thank you.
I'll see what I can do on my side. I just prefer to take precaution in advance
