### ISSUE TITLE
URGENT! You removed support for 2.1.23

### ISSUE THREAD

**Issue by drmarmalademd** [hssm/advanced-browser#77]
Since your most recent update, you have removed support for 2.1.23 and by default, I can no longer enable this add-on because Anki will not allow me to. On the add-on page, your support is 2.1.0-2.1.22 and 2.1.24+.

Please update the add-on ASAP to enable 2.1.23 support.

**Comment by hssm** [comment]
Thanks for pointing this out. It should be fixed now.

**Comment by drmarmalademd** [comment]
THANKS! Much appreciated - I rely on this add-on daily! Cheers.
