### ISSUE TITLE
Error when i try to open the browser

### ISSUE THREAD

**Issue by aPaci95** [hssm/advanced-browser#80]
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-31 14:23:02

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 31, in cmd
  File "aqt\webview.py", line 97, in _onCmd
  File "aqt\webview.py", line 500, in _onBridgeCmd
  File "aqt\toolbar.py", line 154, in _linkHandler
  File "aqt\toolbar.py", line 172, in _browseLinkHandler
  File "aqt\main.py", line 991, in onBrowse
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\354407385\__init__.py", line 60, in open
    return function(name, *args, **kwargs)
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\354407385\__init__.py", line 70, in openMany
    instance = creator(*args, **kwargs)
  File "C:\Users\pacia\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 292, in __init__
    origInit(self, mw)
TypeError: newBrowserInit() takes 2 positional arguments but 3 were given

---------------
Also this is the debug info

    
    Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-03-31 14:23:02
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    3 add-ons merged quicker anki explain deletion explain database check ['777545149', 2019-10-26T11:31, 'None', '']
    Advanced Browser ['874215009', 2020-02-20T23:39, 'None', '']
    Anki Killstreaks ['579111794', 2020-03-10T18:20, 'None', mod]
    Anki Simulator ['anki_simulator', 2020-03-28T20:47, 'None', '']
    AwesomeTTS Google Cloud Text-to-Speech unofficial ['814349176', 2020-02-24T13:36, 'None', '']
    Batch Editing ['291119185', 2019-10-26T11:34, 'None', '']
    BetterTags ['bettertags', 2020-01-28T21:30, 'None', '']
    Browser Resizer ['1435775540', 2020-02-08T01:39, 'None', mod]
    Card Layout Editor - syntax highlighting monospace font ['1483620388', 2018-01-17T16:11, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2019-10-26T11:29, 'None', '']
    Create link in note to display specific search  in browser ['2053932397', 2020-03-29T19:56, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2020-03-11T06:05, 'None', mod]
    Customize Sidebar ['1988760596', 2020-01-18T00:27, 'None', '']
    Dancing Baloney Allows changing wallpapers with live preview ['378638814', 2020-03-27T06:28, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2020-03-20T10:16, 'None', mod]
    Fastbar another toolbar for Anki 21 beta ['1955978390', 2019-10-26T19:51, 'None', '']
    Graphical form to change add-on configuration ['1014777615', 2020-03-19T11:22, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2019-10-26T11:24, 'None', '']
    Hitmarkers ['1776869150', 2020-03-11T19:57, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2019-10-26T11:25, 'None', '']
    Keep model of add cards ['424778276', 2019-03-22T14:07, 'None', '']
    Load Balanced Scheduler ['208879074', 2019-10-26T11:27, 'None', '']
    Maximum image heightwidth in card editor ['229181581', 2020-02-20T09:10, 'None', mod]
    Mini Format Pack ['295889520', 2019-10-26T11:38, 'None', mod]
    Minimal Flat Big Buttons compatible with ReMemorize Buttons ['1042429613', 2020-03-11T12:09, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2020-01-21T17:54, 'None', '']
    More Overview Stats 21 ['738807903', 2019-10-26T11:27, 'None', '']
    Multi-column note editor ['3491767031', 2020-01-22T09:53, 'None', mod]
    No Distractions Full Screen Clean review interface  TabletTouch support ['1049863218', 2020-03-30T22:34, 'v4.1.1', mod]
    Open Added Today from Reviewer ['861864770', 2019-02-22T20:19, 'None', '']
    Opening the same window multiple time ['354407385', 2020-03-09T12:57, 'None', '']
    Quick note and deck buttons Fork for 21 ['1331140127', 2020-02-22T12:32, 'None', mod]
    ReMemorize Buttons ['rememorize_btn', 2019-04-30T09:32, 'None', mod]
    ReMemorize Rescheduler with sibling and logging v130 ['323586997', 2020-02-04T15:06, 'None', mod]
    Review Heatmap ['review_heatmap', 2018-10-28T23:06, 'None', '']
    Straight Reward ['957961234', 2020-03-17T18:38, 'None', mod]
    Tag Entry Enhancements ['1348430474', 2019-10-26T11:54, 'None', '']
    remove linebreaks  do word wrap fork for 21 ['2028179508', 2019-10-26T11:53, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1014777615 1042429613 1049863218 1331140127 1348430474 1374772155 1435775540 1483620388 1556734708 1776869150 1955978390 1988760596 2028179508 2053932397 208879074 225180905 229181581 24411424 291119185 295889520 323586997 3491767031 354407385 378638814 385888438 424778276 579111794 738807903 777545149 814349176 861263371 861864770 874215009 957961234
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Copy Fields ['1898445115', 2019-10-26T11:44, 'None', '']
    Advanced note editor Multi-column Frozen fields LaTeXs result in editor ['2064123047', 2020-02-16T04:17, 'None', '']
    AnJoy ['anjoy', 2019-07-31T23:02, 'None', '']
    Anki IPA ['799647424', 2020-03-10T13:06, 'None', '']
    Anki Zoom ['538879081', 2020-03-29T04:34, 'v1.1.3', mod]
    AnkiWebView Inspector ['31746032', 2019-10-29T23:59, 'None', '']
    AutoDefine - Automatically define vocabulary words with pronunciations and image ['2136497008', 2019-06-04T08:06, 'None', mod]
    Batch Download Pictures From Google Images ['561924305', 2020-03-10T14:06, 'None', mod]
    Batch Remove Formatting eg bold italics etc ['1734822644', 2019-10-26T11:22, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T13:37, 'None', '']
    Deadline2 ['723639202', 2020-03-27T02:19, 'None', '']
    Duplicate Selected Notes ['2126361512', 2019-10-26T12:38, 'None', '']
    Enhance main window ['877182321', 2020-02-16T03:51, 'None', mod]
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T05:10, 'None', '']
    Field History ['1247884413', 2019-10-26T11:29, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T05:12, 'None', '']
    Ignore accents in browser search ['1924690148', 2020-01-18T00:13, 'None', '']
    Keep card displayed in reviewer until it is modified ['1894745652', 2020-01-24T02:22, 'None', '']
    Merge two notes into a single note ['1482505492', 2020-03-28T11:48, 'None', mod]
    Redesign ['1914733489', 2020-02-29T23:46, 'None', '']
    Resize images in editor ['1103084694', 2020-03-21T09:58, 'None', mod]
    Search in formatted text in any fields ['1126516755', 2020-03-10T22:36, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-10-26T11:53, 'None', '']
    Syntax Highlighting for Code ['1463041493', 2018-10-07T03:31, 'None', '']
    Visual Feedback for Reviews ['review_feedback', 2020-01-29T20:43, 'None', '']
    load balancer ['1417170896', 2020-02-17T21:02, 'None', '']

**Comment by hssm** [comment]
Seems to be conflicting with the `Opening the same window multiple time` add-on. @Arthur-Milchior

**Comment by Arthur-Milchior** [comment]
@aPaci95 if you do multiple bug report, please put a link between them. So that hssm and myself Don t have to do the same work and can see what the other answered.
My link is here https://github.com/Arthur-Milchior/anki-Multiple-Windows/issues/3#issuecomment-606847212
