### ISSUE TITLE
New Column Suggestion: Flags

### ISSUE THREAD

**Issue by jamiekoi** [hssm/advanced-browser#81]
Hi,

I was wondering if you could add a new column "Flags" to allow sorting by flags (i.e., show all flag:1 first, then flag:2, then flag:3 ...etc in ascending or descending order)

My use case for it:
I have topics tagged in my collection, for example "lung cancer". I flag:
Cards relating to "symptoms" with a flag:1
Cards relating to "investigations" with flag:2
Cards relating to "treatment" with flag:3

This new column would allow me to go to tag:lung_cancer, and sort by flag. so that when I preview them in the browser, I can see them in orders symptoms>investigations>treatment which will allow me to quickly to identify if I need to add cards to the "symptoms"...etc.

I've been advised to tag cards by "symptoms", "investigation", "treatment", and then with your add-on I can easily sort by tags, but this has 2 problems:

1. tags cannot be shown as colours like flags do, which are easy to spot 
2. some cards already have many tags, and Advanced browser will sort by the first alphabetical tag 

If it is not possible to add this column, could you point me in the right direction?
Thanks!

**Comment by hssm** [comment]
Good idea. Should be possible. I'll see what I can do.

**Comment by hssm** [comment]
The version of the add-on you have now has support for this column, but it's hidden as an "internal field" for cards which you have to enable in the add-on's configuration with the add-on manager.

I've just uploaded a new version of the add-on to AnkiWeb that makes this a standard column offered by the add-on and improved the sorting of it. However, the latest releases of the add-on only work on Anki 2.1.24 which is currently in beta. So you will either have to wait until it is released or [download a beta release](https://betas.ankiweb.net/#/).
