### ISSUE TITLE
Card "Added" date column?

### ISSUE THREAD

**Issue by aleksejrs** [hssm/advanced-browser#84]
There is a "Created" column, but it shows the creation date of the note. Is that because I add the cards using Anki 2.0.x, or would an "Added" column be different?

**Comment by hssm** [comment]
Sorry, I don't understand the question. What do you expect an "added" column to contain?

**Comment by aleksejrs** [comment]
E.g., I created a note on 2017-01-01. But I edited it today so that a new card appeared on 2020-04-21.

Now, the Created column of both cards shows 2017-01-01. I expect the Added column to contain 2020-04-21.

**Comment by hssm** [comment]
I've uploaded a new version (for Anki 2.1.24) to AnkiWeb that adds columns for card creation (date-only or date+time).

**Comment by aleksejrs** [comment]
Thanks, I'll check it one day…
