### ISSUE TITLE
feature request - search by "edited"

### ISSUE THREAD

**Issue by RonilPatel7** [hssm/advanced-browser#95]
I was wondering if it would be possible to make it so cards could be searched by date "edited" similar to the way they can be searched by date added?

My goal is to to create a filtered deck based on recently edited cards.

I found this post on reddit as well:
https://www.reddit.com/r/Anki/comments/4uribl/how_to_search_for_edited_cards/

**Comment by hssm** [comment]
I don't think this makes sense, unless I am missing some important detail.

When you edit a card, you are editing the underlying note, so the existing `Edited` column already provides that data for you. Cards themselves do have a modification time, but I think that includes any card data (like interval or ease) that get updated with each rep (used mainly for syncing and not users).

**Comment by AnKingMed** [comment]
@hssm I think I understand what @RonilPatel7 is getting at with this. He wants to have the data in that edited column, but in such a way that it could easily be used with filtered decks. For example, if you wanted a filtered deck of all cards edited in the last 10 days, you'd have to retag and sort those cards in the browser every day. It would be more simple to just have edited:10 or something (similar to the built in added:10 function) that allows you to see all cards edited in the last day. 

Does that make a bit more sense?  I see the value in this. I get emails from people regularly asking about this topic

**Comment by hssm** [comment]
Yep, that makes sense. I was fixated on columns and didn't consider actual card searching.

It looks like this has been added upstream so I will close this.
