### ISSUE TITLE
Can't Select or Copy table content

### ISSUE THREAD

**Issue by SEE-ICT** [hssm/advanced-browser#99]
Double clicking on the data in a column produces no response. Configuration is:

{
    "Show internal fields": true,
    "Table content": "Selectable",
    "Use a single list for fields": false
}

I know that the add on is responding to changes in configuration, because I changed "Show internal fields" to "true", and that worked, internal fields were shown. I did not have to change "Table content" key's value to "Selectable", because it was it already was set to that value. 

Is there something I'm missing here?

Thanks for any help that you can give.

**Comment by hssm** [comment]
Try clicking on the table cell and copying the text with a keyboard shortcut (`Ctrl+C`). I believe it will work. There's no visual indication that the cell is selected, even though it is.

I've tried to do something about this but Anki overrides the style with its own row colouring, so not too sure what the right approach is to solve this visual issue.

**Comment by SEE-ICT** [comment]
When I Ctrl + C, Anki throws an error that implicates the Copy Note add-on. Details are below. Disabling Copy Note, clicking on the table cell and using Ctrl + C works with, e.g., the Due and Sort Field fields. But it does not work with the Card ID or Note ID fields, which are the ones that I wish to use.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-01 17:22:57

Caught exception:
Traceback (most recent call last):
  File "D:\Program Data\Anki\addons21\1566928056\copyNote.py", line 65, in <lambda>
    a.triggered.connect(lambda: copyNotes(browser.selectedNotes()))
  File "D:\Program Data\Anki\addons21\1566928056\copyNote.py", line 52, in copyNotes
    copyNote(nid)
  File "D:\Program Data\Anki\addons21\1566928056\copyNote.py", line 83, in copyNote
    note.flush()
  File "anki\notes.py", line 68, in flush
  File "anki\rsbackend_gen.py", line 344, in update_note
  File "anki\rsbackend.py", line 265, in _run_command
anki.rsbackend.NotFoundError

**Comment by SEE-ICT** [comment]
Just checking to see if there are any thoughts on the above. It would be really helpful to be able to copy Note IDs and Card IDs!

**Comment by hssm** [comment]
I have found the source of the problem. I'll issue a fix in the next few days.

**Comment by hssm** [comment]
Fixed. I've published an update to AnkiWeb.

**Comment by SEE-ICT** [comment]
Great! Much appreciated. I'll download it now and put it to work!
